/*
	JUL Comment System (JCS) version 1.1.9
	Copyright (c) 2015 - 2016 The Zonebuilder (zone.builder@gmx.com)
	http://sourceforge.net/projects/jul-comments/
	Licenses: GPLv2 or later; LGPLv3 or later (http://sourceforge.net/p/jul-comments/wiki/License/)
*/
/**
	@fileOverview	This file holds the configuration for the 'About' window
*/
/* jshint browser: true, curly: true, eqeqeq: true, expr: true, funcscope: true, immed: true, latedef: true, loopfunc: true,  
	onevar: true, newcap: true, noarg: true, node: true, strict: true, trailing: true, undef: true, unused: vars, wsh: true */
/* globals ample, JUL */

(function() {
'use strict';

/* generated by JCS version 1.1.9 */

/**
	About window module
	@namespace
	@name	JUL.Comments.about
*/
JUL.ns('JUL.Comments.about');

/**
	UI configuration for 'About' window
	@type	Object
*/
JUL.Comments.about.ui = {
	tag: 'window',
	id: 'window-about',
	css: 'logo-bg',
	hidden: true,
	title: 'About',
	width: 500,
	height: 195,
	'aml:resizable': false,
	orient: 'horizontal',
	children: [
		{tag: 'vbox', width: 214, children: [
			{xclass: 'html', tag: 'div', style: 'padding: 30px 0 0 30px', flex: 1, children: [
				{xclass: 'html', tag: 'img', width: 160, height: 120, alt: JUL.Comments.title, src: 'media/braces120.png'}
			]}
		]},
		{tag: 'vbox', flex: 1, children: [
			{tag: 'spacer', height: 25},
			{tag: 'description', css: 'logo-title', value: JUL.Comments.title},
			{tag: 'description', value: JUL.Comments.version},
			{tag: 'description',
			 html: 'Copyright &copy; 2015 - 2016 <a target="_blank" href="' + ample.$encodeXMLCharacters(JUL.Comments.config.zb_link) + '">The Zonebuilder</a>'},
			{tag: 'description',
			 html: 'Powered by <a target="_blank" href="http://www.amplesdk.com/">Ample SDK</a> &amp; <a target="_blank" href="http://kohanaframework.org/">Kohana PHP</a>'}
		]}
	],
	listeners: {
		click: function(oEvent) {
			if (oEvent.target.nodeName !== 'a') { this.hide(oEvent); }
		}
	}
};

JUL.apply(JUL.Comments.about, /** @lends JUL.Comments.about */ {});

})();

/* end JUL.Comments.about.js */
